# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: phoenixapi/protos/bot/controller.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'phoenixapi/protos/bot/controller.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&phoenixapi/protos/bot/controller.proto\x12\x0bphoenix.bot\x1a\x1bgoogle/protobuf/empty.proto\",\n\x13LoadSettingsRequest\x12\x15\n\rini_file_path\x18\x01 \x01(\t2\xb4\x03\n\nController\x12\x43\n\x0fStartFarmingBot\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12\x42\n\x0eStopFarmingBot\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12\x46\n\x12\x43ontinueFarmingBot\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12\x44\n\x10StartMinigameBot\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12\x43\n\x0fStopMinigameBot\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12J\n\x0cLoadSettings\x12 .phoenix.bot.LoadSettingsRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'phoenixapi.protos.bot.controller_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOADSETTINGSREQUEST']._serialized_start=84
  _globals['_LOADSETTINGSREQUEST']._serialized_end=128
  _globals['_CONTROLLER']._serialized_start=131
  _globals['_CONTROLLER']._serialized_end=567
# @@protoc_insertion_point(module_scope)
