# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from phoenixapi.protos.game import inventorymanager_pb2 as phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in phoenixapi/protos/game/inventorymanager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventoryManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGold = channel.unary_unary(
                '/phoenix.game.InventoryManager/GetGold',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.GoldResponse.FromString,
                _registered_method=True)
        self.GetEquipTab = channel.unary_unary(
                '/phoenix.game.InventoryManager/GetEquipTab',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.InvSlotList.FromString,
                _registered_method=True)
        self.GetMainTab = channel.unary_unary(
                '/phoenix.game.InventoryManager/GetMainTab',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.InvSlotList.FromString,
                _registered_method=True)
        self.GetEtcTab = channel.unary_unary(
                '/phoenix.game.InventoryManager/GetEtcTab',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.InvSlotList.FromString,
                _registered_method=True)
        self.GetInventorySlot = channel.unary_unary(
                '/phoenix.game.InventoryManager/GetInventorySlot',
                request_serializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.InventorySlotRequest.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.InvSlot.FromString,
                _registered_method=True)
        self.FindItem = channel.unary_unary(
                '/phoenix.game.InventoryManager/FindItem',
                request_serializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.FindItemRequest.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.InvSlot.FromString,
                _registered_method=True)
        self.UseItem = channel.unary_unary(
                '/phoenix.game.InventoryManager/UseItem',
                request_serializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.UseItemRequest.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.UseItemResponse.FromString,
                _registered_method=True)
        self.UseItemOnTarget = channel.unary_unary(
                '/phoenix.game.InventoryManager/UseItemOnTarget',
                request_serializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.UseItemOnTargetRequest.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.UseItemResponse.FromString,
                _registered_method=True)


class InventoryManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetGold(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEquipTab(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMainTab(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEtcTab(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInventorySlot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UseItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UseItemOnTarget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGold': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGold,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.GoldResponse.SerializeToString,
            ),
            'GetEquipTab': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEquipTab,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.InvSlotList.SerializeToString,
            ),
            'GetMainTab': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMainTab,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.InvSlotList.SerializeToString,
            ),
            'GetEtcTab': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEtcTab,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.InvSlotList.SerializeToString,
            ),
            'GetInventorySlot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInventorySlot,
                    request_deserializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.InventorySlotRequest.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.InvSlot.SerializeToString,
            ),
            'FindItem': grpc.unary_unary_rpc_method_handler(
                    servicer.FindItem,
                    request_deserializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.FindItemRequest.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.InvSlot.SerializeToString,
            ),
            'UseItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UseItem,
                    request_deserializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.UseItemRequest.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.UseItemResponse.SerializeToString,
            ),
            'UseItemOnTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.UseItemOnTarget,
                    request_deserializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.UseItemOnTargetRequest.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.UseItemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'phoenix.game.InventoryManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('phoenix.game.InventoryManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InventoryManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetGold(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.InventoryManager/GetGold',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.GoldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEquipTab(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.InventoryManager/GetEquipTab',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.InvSlotList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMainTab(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.InventoryManager/GetMainTab',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.InvSlotList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEtcTab(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.InventoryManager/GetEtcTab',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.InvSlotList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInventorySlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.InventoryManager/GetInventorySlot',
            phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.InventorySlotRequest.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.InvSlot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.InventoryManager/FindItem',
            phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.FindItemRequest.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.InvSlot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UseItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.InventoryManager/UseItem',
            phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.UseItemRequest.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.UseItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UseItemOnTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.InventoryManager/UseItemOnTarget',
            phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.UseItemOnTargetRequest.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_inventorymanager__pb2.UseItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
