# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from phoenixapi.protos.game import packetmanager_pb2 as phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in phoenixapi/protos/game/packetmanager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PacketManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_unary(
                '/phoenix.game.PacketManager/Subscribe',
                request_serializer=phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Identifier.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Unsubscribe = channel.unary_unary(
                '/phoenix.game.PacketManager/Unsubscribe',
                request_serializer=phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Identifier.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetPendingSendPackets = channel.unary_stream(
                '/phoenix.game.PacketManager/GetPendingSendPackets',
                request_serializer=phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Identifier.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Packet.FromString,
                _registered_method=True)
        self.GetPendingRecvPackets = channel.unary_stream(
                '/phoenix.game.PacketManager/GetPendingRecvPackets',
                request_serializer=phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Identifier.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Packet.FromString,
                _registered_method=True)
        self.Send = channel.unary_unary(
                '/phoenix.game.PacketManager/Send',
                request_serializer=phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Packet.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Recv = channel.unary_unary(
                '/phoenix.game.PacketManager/Recv',
                request_serializer=phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Packet.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class PacketManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unsubscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingSendPackets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingRecvPackets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recv(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PacketManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Identifier.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Unsubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Unsubscribe,
                    request_deserializer=phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Identifier.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetPendingSendPackets': grpc.unary_stream_rpc_method_handler(
                    servicer.GetPendingSendPackets,
                    request_deserializer=phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Identifier.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Packet.SerializeToString,
            ),
            'GetPendingRecvPackets': grpc.unary_stream_rpc_method_handler(
                    servicer.GetPendingRecvPackets,
                    request_deserializer=phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Identifier.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Packet.SerializeToString,
            ),
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Packet.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Recv': grpc.unary_unary_rpc_method_handler(
                    servicer.Recv,
                    request_deserializer=phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Packet.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'phoenix.game.PacketManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('phoenix.game.PacketManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PacketManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.PacketManager/Subscribe',
            phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Identifier.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unsubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.PacketManager/Unsubscribe',
            phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Identifier.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingSendPackets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/phoenix.game.PacketManager/GetPendingSendPackets',
            phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Identifier.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Packet.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingRecvPackets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/phoenix.game.PacketManager/GetPendingRecvPackets',
            phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Identifier.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Packet.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.PacketManager/Send',
            phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Packet.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recv(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.PacketManager/Recv',
            phoenixapi_dot_protos_dot_game_dot_packetmanager__pb2.Packet.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
