# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: phoenixapi/protos/game/packetmanager.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'phoenixapi/protos/game/packetmanager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*phoenixapi/protos/game/packetmanager.proto\x12\x0cphoenix.game\x1a\x1bgoogle/protobuf/empty.proto\"\x18\n\nIdentifier\x12\n\n\x02id\x18\x01 \x01(\t\"\x16\n\x06Packet\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\x9d\x03\n\rPacketManager\x12?\n\tSubscribe\x12\x18.phoenix.game.Identifier\x1a\x16.google.protobuf.Empty\"\x00\x12\x41\n\x0bUnsubscribe\x12\x18.phoenix.game.Identifier\x1a\x16.google.protobuf.Empty\"\x00\x12K\n\x15GetPendingSendPackets\x12\x18.phoenix.game.Identifier\x1a\x14.phoenix.game.Packet\"\x00\x30\x01\x12K\n\x15GetPendingRecvPackets\x12\x18.phoenix.game.Identifier\x1a\x14.phoenix.game.Packet\"\x00\x30\x01\x12\x36\n\x04Send\x12\x14.phoenix.game.Packet\x1a\x16.google.protobuf.Empty\"\x00\x12\x36\n\x04Recv\x12\x14.phoenix.game.Packet\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'phoenixapi.protos.game.packetmanager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IDENTIFIER']._serialized_start=89
  _globals['_IDENTIFIER']._serialized_end=113
  _globals['_PACKET']._serialized_start=115
  _globals['_PACKET']._serialized_end=137
  _globals['_PACKETMANAGER']._serialized_start=140
  _globals['_PACKETMANAGER']._serialized_end=553
# @@protoc_insertion_point(module_scope)
