# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from phoenixapi.protos.game import petmanager_pb2 as phoenixapi_dot_protos_dot_game_dot_petmanager__pb2
from phoenixapi.protos.game import playermanager_pb2 as phoenixapi_dot_protos_dot_game_dot_playermanager__pb2
from phoenixapi.protos import position_pb2 as phoenixapi_dot_protos_dot_position__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in phoenixapi/protos/game/petmanager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PetManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPets = channel.unary_unary(
                '/phoenix.game.PetManager/GetPets',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_petmanager__pb2.PetObjManagerList.FromString,
                _registered_method=True)
        self.GetCurrentPet = channel.unary_unary(
                '/phoenix.game.PetManager/GetCurrentPet',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_petmanager__pb2.PetObjManager.FromString,
                _registered_method=True)
        self.GetCurrentPartner = channel.unary_unary(
                '/phoenix.game.PetManager/GetCurrentPartner',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_petmanager__pb2.PetObjManager.FromString,
                _registered_method=True)
        self.SetPetState = channel.unary_unary(
                '/phoenix.game.PetManager/SetPetState',
                request_serializer=phoenixapi_dot_protos_dot_game_dot_petmanager__pb2.PetStateRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Walk = channel.unary_unary(
                '/phoenix.game.PetManager/Walk',
                request_serializer=phoenixapi_dot_protos_dot_position__pb2.Position.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AutoAttack = channel.unary_unary(
                '/phoenix.game.PetManager/AutoAttack',
                request_serializer=phoenixapi_dot_protos_dot_game_dot_petmanager__pb2.AutoAttackRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.PetAttack = channel.unary_unary(
                '/phoenix.game.PetManager/PetAttack',
                request_serializer=phoenixapi_dot_protos_dot_game_dot_playermanager__pb2.AttackRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.PartnerAttack = channel.unary_unary(
                '/phoenix.game.PetManager/PartnerAttack',
                request_serializer=phoenixapi_dot_protos_dot_game_dot_playermanager__pb2.AttackRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class PetManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentPet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentPartner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Walk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AutoAttack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PetAttack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartnerAttack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PetManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPets,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_petmanager__pb2.PetObjManagerList.SerializeToString,
            ),
            'GetCurrentPet': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentPet,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_petmanager__pb2.PetObjManager.SerializeToString,
            ),
            'GetCurrentPartner': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentPartner,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_petmanager__pb2.PetObjManager.SerializeToString,
            ),
            'SetPetState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPetState,
                    request_deserializer=phoenixapi_dot_protos_dot_game_dot_petmanager__pb2.PetStateRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Walk': grpc.unary_unary_rpc_method_handler(
                    servicer.Walk,
                    request_deserializer=phoenixapi_dot_protos_dot_position__pb2.Position.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AutoAttack': grpc.unary_unary_rpc_method_handler(
                    servicer.AutoAttack,
                    request_deserializer=phoenixapi_dot_protos_dot_game_dot_petmanager__pb2.AutoAttackRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'PetAttack': grpc.unary_unary_rpc_method_handler(
                    servicer.PetAttack,
                    request_deserializer=phoenixapi_dot_protos_dot_game_dot_playermanager__pb2.AttackRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'PartnerAttack': grpc.unary_unary_rpc_method_handler(
                    servicer.PartnerAttack,
                    request_deserializer=phoenixapi_dot_protos_dot_game_dot_playermanager__pb2.AttackRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'phoenix.game.PetManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('phoenix.game.PetManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PetManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.PetManager/GetPets',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_petmanager__pb2.PetObjManagerList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentPet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.PetManager/GetCurrentPet',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_petmanager__pb2.PetObjManager.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentPartner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.PetManager/GetCurrentPartner',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_petmanager__pb2.PetObjManager.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.PetManager/SetPetState',
            phoenixapi_dot_protos_dot_game_dot_petmanager__pb2.PetStateRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Walk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.PetManager/Walk',
            phoenixapi_dot_protos_dot_position__pb2.Position.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AutoAttack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.PetManager/AutoAttack',
            phoenixapi_dot_protos_dot_game_dot_petmanager__pb2.AutoAttackRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PetAttack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.PetManager/PetAttack',
            phoenixapi_dot_protos_dot_game_dot_playermanager__pb2.AttackRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PartnerAttack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.PetManager/PartnerAttack',
            phoenixapi_dot_protos_dot_game_dot_playermanager__pb2.AttackRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
