# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from phoenixapi.protos.game import playermanager_pb2 as phoenixapi_dot_protos_dot_game_dot_playermanager__pb2
from phoenixapi.protos import position_pb2 as phoenixapi_dot_protos_dot_position__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in phoenixapi/protos/game/playermanager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlayerManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPlayerObjManager = channel.unary_unary(
                '/phoenix.game.PlayerManager/GetPlayerObjManager',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_playermanager__pb2.PlayerObjManager.FromString,
                _registered_method=True)
        self.ResetPlayerState = channel.unary_unary(
                '/phoenix.game.PlayerManager/ResetPlayerState',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Walk = channel.unary_unary(
                '/phoenix.game.PlayerManager/Walk',
                request_serializer=phoenixapi_dot_protos_dot_position__pb2.Position.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Attack = channel.unary_unary(
                '/phoenix.game.PlayerManager/Attack',
                request_serializer=phoenixapi_dot_protos_dot_game_dot_playermanager__pb2.AttackRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.PickUp = channel.unary_unary(
                '/phoenix.game.PlayerManager/PickUp',
                request_serializer=phoenixapi_dot_protos_dot_game_dot_playermanager__pb2.PickUpRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Collect = channel.unary_unary(
                '/phoenix.game.PlayerManager/Collect',
                request_serializer=phoenixapi_dot_protos_dot_game_dot_playermanager__pb2.CollectRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Target = channel.unary_unary(
                '/phoenix.game.PlayerManager/Target',
                request_serializer=phoenixapi_dot_protos_dot_game_dot_playermanager__pb2.TargetRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class PlayerManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPlayerObjManager(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetPlayerState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Walk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Attack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PickUp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Collect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Target(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlayerManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPlayerObjManager': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlayerObjManager,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_playermanager__pb2.PlayerObjManager.SerializeToString,
            ),
            'ResetPlayerState': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetPlayerState,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Walk': grpc.unary_unary_rpc_method_handler(
                    servicer.Walk,
                    request_deserializer=phoenixapi_dot_protos_dot_position__pb2.Position.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Attack': grpc.unary_unary_rpc_method_handler(
                    servicer.Attack,
                    request_deserializer=phoenixapi_dot_protos_dot_game_dot_playermanager__pb2.AttackRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'PickUp': grpc.unary_unary_rpc_method_handler(
                    servicer.PickUp,
                    request_deserializer=phoenixapi_dot_protos_dot_game_dot_playermanager__pb2.PickUpRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Collect': grpc.unary_unary_rpc_method_handler(
                    servicer.Collect,
                    request_deserializer=phoenixapi_dot_protos_dot_game_dot_playermanager__pb2.CollectRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Target': grpc.unary_unary_rpc_method_handler(
                    servicer.Target,
                    request_deserializer=phoenixapi_dot_protos_dot_game_dot_playermanager__pb2.TargetRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'phoenix.game.PlayerManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('phoenix.game.PlayerManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlayerManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPlayerObjManager(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.PlayerManager/GetPlayerObjManager',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_playermanager__pb2.PlayerObjManager.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetPlayerState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.PlayerManager/ResetPlayerState',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Walk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.PlayerManager/Walk',
            phoenixapi_dot_protos_dot_position__pb2.Position.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Attack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.PlayerManager/Attack',
            phoenixapi_dot_protos_dot_game_dot_playermanager__pb2.AttackRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PickUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.PlayerManager/PickUp',
            phoenixapi_dot_protos_dot_game_dot_playermanager__pb2.PickUpRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Collect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.PlayerManager/Collect',
            phoenixapi_dot_protos_dot_game_dot_playermanager__pb2.CollectRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Target(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.PlayerManager/Target',
            phoenixapi_dot_protos_dot_game_dot_playermanager__pb2.TargetRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
