# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from phoenixapi.protos.game import entities_pb2 as phoenixapi_dot_protos_dot_game_dot_entities__pb2
from phoenixapi.protos.game import scenemanager_pb2 as phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in phoenixapi/protos/game/scenemanager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SceneManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPlayers = channel.unary_unary(
                '/phoenix.game.SceneManager/GetPlayers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.PlayerList.FromString,
                _registered_method=True)
        self.GetMonsters = channel.unary_unary(
                '/phoenix.game.SceneManager/GetMonsters',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.MonsterList.FromString,
                _registered_method=True)
        self.GetItems = channel.unary_unary(
                '/phoenix.game.SceneManager/GetItems',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.ItemList.FromString,
                _registered_method=True)
        self.GetNpcs = channel.unary_unary(
                '/phoenix.game.SceneManager/GetNpcs',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.NpcList.FromString,
                _registered_method=True)
        self.FindPlayer = channel.unary_unary(
                '/phoenix.game.SceneManager/FindPlayer',
                request_serializer=phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.FindRequest.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_entities__pb2.Player.FromString,
                _registered_method=True)
        self.FindMonster = channel.unary_unary(
                '/phoenix.game.SceneManager/FindMonster',
                request_serializer=phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.FindRequest.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_entities__pb2.Monster.FromString,
                _registered_method=True)
        self.FindItem = channel.unary_unary(
                '/phoenix.game.SceneManager/FindItem',
                request_serializer=phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.FindRequest.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_entities__pb2.Item.FromString,
                _registered_method=True)
        self.FindNpc = channel.unary_unary(
                '/phoenix.game.SceneManager/FindNpc',
                request_serializer=phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.FindRequest.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_entities__pb2.Npc.FromString,
                _registered_method=True)
        self.GetAllBosses = channel.unary_unary(
                '/phoenix.game.SceneManager/GetAllBosses',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.MonsterList.FromString,
                _registered_method=True)
        self.GetMapGrid = channel.unary_unary(
                '/phoenix.game.SceneManager/GetMapGrid',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.MapGrid.FromString,
                _registered_method=True)


class SceneManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPlayers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMonsters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNpcs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindPlayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindMonster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindNpc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllBosses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMapGrid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SceneManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPlayers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlayers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.PlayerList.SerializeToString,
            ),
            'GetMonsters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMonsters,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.MonsterList.SerializeToString,
            ),
            'GetItems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItems,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.ItemList.SerializeToString,
            ),
            'GetNpcs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNpcs,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.NpcList.SerializeToString,
            ),
            'FindPlayer': grpc.unary_unary_rpc_method_handler(
                    servicer.FindPlayer,
                    request_deserializer=phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.FindRequest.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_entities__pb2.Player.SerializeToString,
            ),
            'FindMonster': grpc.unary_unary_rpc_method_handler(
                    servicer.FindMonster,
                    request_deserializer=phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.FindRequest.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_entities__pb2.Monster.SerializeToString,
            ),
            'FindItem': grpc.unary_unary_rpc_method_handler(
                    servicer.FindItem,
                    request_deserializer=phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.FindRequest.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_entities__pb2.Item.SerializeToString,
            ),
            'FindNpc': grpc.unary_unary_rpc_method_handler(
                    servicer.FindNpc,
                    request_deserializer=phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.FindRequest.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_entities__pb2.Npc.SerializeToString,
            ),
            'GetAllBosses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllBosses,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.MonsterList.SerializeToString,
            ),
            'GetMapGrid': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMapGrid,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.MapGrid.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'phoenix.game.SceneManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('phoenix.game.SceneManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SceneManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPlayers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.SceneManager/GetPlayers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.PlayerList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMonsters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.SceneManager/GetMonsters',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.MonsterList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.SceneManager/GetItems',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.ItemList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNpcs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.SceneManager/GetNpcs',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.NpcList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindPlayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.SceneManager/FindPlayer',
            phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.FindRequest.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_entities__pb2.Player.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindMonster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.SceneManager/FindMonster',
            phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.FindRequest.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_entities__pb2.Monster.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.SceneManager/FindItem',
            phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.FindRequest.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_entities__pb2.Item.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindNpc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.SceneManager/FindNpc',
            phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.FindRequest.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_entities__pb2.Npc.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllBosses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.SceneManager/GetAllBosses',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.MonsterList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMapGrid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phoenix.game.SceneManager/GetMapGrid',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            phoenixapi_dot_protos_dot_game_dot_scenemanager__pb2.MapGrid.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
