# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: phoenixapi/protos/game/scenemanager.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'phoenixapi/protos/game/scenemanager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from phoenixapi.protos.game import entities_pb2 as phoenixapi_dot_protos_dot_game_dot_entities__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)phoenixapi/protos/game/scenemanager.proto\x12\x0cphoenix.game\x1a\x1bgoogle/protobuf/empty.proto\x1a%phoenixapi/protos/game/entities.proto\"\x19\n\x0b\x46indRequest\x12\n\n\x02id\x18\x01 \x01(\x11\"I\n\x07MapGrid\x12\r\n\x05width\x18\x01 \x01(\x11\x12\x0e\n\x06height\x18\x02 \x01(\x11\x12\x1f\n\x04rows\x18\x03 \x03(\x0b\x32\x11.phoenix.game.Row\",\n\x03Row\x12%\n\x05\x63\x65lls\x18\x01 \x03(\x0e\x32\x16.phoenix.game.CellType\"<\n\nPlayerList\x12.\n\x07players\x18\x01 \x03(\x0b\x32\x1d.phoenix.game.entities.Player\"?\n\x0bMonsterList\x12\x30\n\x08monsters\x18\x01 \x03(\x0b\x32\x1e.phoenix.game.entities.Monster\"3\n\x07NpcList\x12(\n\x04npcs\x18\x01 \x03(\x0b\x32\x1a.phoenix.game.entities.Npc\"6\n\x08ItemList\x12*\n\x05items\x18\x01 \x03(\x0b\x32\x1b.phoenix.game.entities.Item*T\n\x08\x43\x65llType\x12\x16\n\x12\x43\x45LL_TYPE_WALKABLE\x10\x00\x12\x16\n\x12\x43\x45LL_TYPE_OBSTACLE\x10\x01\x12\x18\n\x14\x43\x45LL_TYPE_OBSTACLE_2\x10\x02\x32\xb2\x05\n\x0cSceneManager\x12@\n\nGetPlayers\x12\x16.google.protobuf.Empty\x1a\x18.phoenix.game.PlayerList\"\x00\x12\x42\n\x0bGetMonsters\x12\x16.google.protobuf.Empty\x1a\x19.phoenix.game.MonsterList\"\x00\x12<\n\x08GetItems\x12\x16.google.protobuf.Empty\x1a\x16.phoenix.game.ItemList\"\x00\x12:\n\x07GetNpcs\x12\x16.google.protobuf.Empty\x1a\x15.phoenix.game.NpcList\"\x00\x12H\n\nFindPlayer\x12\x19.phoenix.game.FindRequest\x1a\x1d.phoenix.game.entities.Player\"\x00\x12J\n\x0b\x46indMonster\x12\x19.phoenix.game.FindRequest\x1a\x1e.phoenix.game.entities.Monster\"\x00\x12\x44\n\x08\x46indItem\x12\x19.phoenix.game.FindRequest\x1a\x1b.phoenix.game.entities.Item\"\x00\x12\x42\n\x07\x46indNpc\x12\x19.phoenix.game.FindRequest\x1a\x1a.phoenix.game.entities.Npc\"\x00\x12\x43\n\x0cGetAllBosses\x12\x16.google.protobuf.Empty\x1a\x19.phoenix.game.MonsterList\"\x00\x12=\n\nGetMapGrid\x12\x16.google.protobuf.Empty\x1a\x15.phoenix.game.MapGrid\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'phoenixapi.protos.game.scenemanager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CELLTYPE']._serialized_start=511
  _globals['_CELLTYPE']._serialized_end=595
  _globals['_FINDREQUEST']._serialized_start=127
  _globals['_FINDREQUEST']._serialized_end=152
  _globals['_MAPGRID']._serialized_start=154
  _globals['_MAPGRID']._serialized_end=227
  _globals['_ROW']._serialized_start=229
  _globals['_ROW']._serialized_end=273
  _globals['_PLAYERLIST']._serialized_start=275
  _globals['_PLAYERLIST']._serialized_end=335
  _globals['_MONSTERLIST']._serialized_start=337
  _globals['_MONSTERLIST']._serialized_end=400
  _globals['_NPCLIST']._serialized_start=402
  _globals['_NPCLIST']._serialized_end=453
  _globals['_ITEMLIST']._serialized_start=455
  _globals['_ITEMLIST']._serialized_end=509
  _globals['_SCENEMANAGER']._serialized_start=598
  _globals['_SCENEMANAGER']._serialized_end=1288
# @@protoc_insertion_point(module_scope)
